# fly.toml app configuration file generated for water-on-route on 2025-09-16T19:19:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'water-on-route'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[# Optional HTTP health checks]
[checks]
  [checks.health]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '10s'
    method = 'get'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
